# Generated by Django 4.1.2 on 2023-06-12 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontour', '0002_contrato_id_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='id_cuenta_viaje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ontour.estado_pago'),
            preserve_default=False,
        ),
    ]
