# Generated by Django 4.1.2 on 2023-06-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontour', '0005_rename_id_curso_pagos_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagos',
            old_name='curso',
            new_name='id_curso',
        ),
    ]
