# Generated by Django 4.1.2 on 2023-06-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontour', '0006_rename_curso_pagos_id_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='actividad',
            fields=[
                ('id_actividad', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('nombre_actividad', models.CharField(max_length=15)),
            ],
        ),
    ]
