# Generated by Django 4.1.2 on 2023-06-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontour', '0007_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='id_actividad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ontour.actividad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='id_actividad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
