# Generated by Django 4.1.2 on 2023-07-11 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontour', '0008_pagos_id_actividad_alter_actividad_id_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado_pago',
            name='id_pago',
        ),
        migrations.AddField(
            model_name='pagos',
            name='id_cuenta_viaje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ontour.estado_pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='id_contrato',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estado_pago',
            name='cantidad_actual',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estado_pago',
            name='cantidad_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estado_pago',
            name='id_cuenta_viaje',
            field=models.AutoField(db_column='IdCuenta', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='id_pago',
            field=models.AutoField(db_column='IdPago', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipo_pago',
            name='id_tipo_pago',
            field=models.AutoField(db_column='IdTipoPago', primary_key=True, serialize=False),
        ),
    ]
